// Do not edit. This file is machine generated by the Resource DLL Wizard.
//---------------------------------------------------------------------------
#define PACKAGE __declspec(package)
#define USERC(FileName) extern PACKAGE _Dummy
#define USERES(FileName) extern PACKAGE _Dummy
#define USEFORMRES(FileName, FormName, AncestorName) extern PACKAGE _Dummy
#pragma hdrstop
int _turboFloat;
//---------------------------------------------------------------------------
/*ITE*/ /*LCID:00000409:00000413*/ /**/
/*ITE*/ /*DFMFileType*/ /*Farchive.dfm*/
/*ITE*/ /*DFMFileType*/ /*Fdetails.dfm*/
/*ITE*/ /*DFMFileType*/ /*Fbase.dfm*/
/*ITE*/ /*DFMFileType*/ /*Fcomplete.dfm*/
/*ITE*/ /*DFMFileType*/ /*Fpending.dfm*/
/*ITE*/ /*DFMFileType*/ /*Ffind.dfm*/
/*ITE*/ /*DFMFileType*/ /*Fmain.dfm*/
/*ITE*/ /*DFMFileType*/ /*Fmdetail.dfm*/
/*ITE*/ /*DFMFileType*/ /*Foptions.dfm*/
/*ITE*/ /*DFMFileType*/ /*Fcodes.dfm*/
/*ITE*/ /*DFMFileType*/ /*Fprint.dfm*/
/*ITE*/ /*DFMFileType*/ /*Frange.dfm*/
/*ITE*/ /*DFMFileType*/ /*Fentries.dfm*/
/*ITE*/ /*DFMFileType*/ /*Fcreated.dfm*/
/*ITE*/ /*DFMFileType*/ /*Fschedule.dfm*/
/*ITE*/ /*DFMFileType*/ /*Femployee.dfm*/
/*ITE*/ /*DFMFileType*/ /*Fimport.dfm*/
/*ITE*/ /*DFMFileType*/ /*Fmail.dfm*/
//---------------------------------------------------------------------------
#pragma resource "Farchive.dfm"
#pragma resource "Fdetails.dfm"
#pragma resource "Fbase.dfm"
#pragma resource "Fcomplete.dfm"
#pragma resource "Fpending.dfm"
#pragma resource "Ffind.dfm"
#pragma resource "Fmain.dfm"
#pragma resource "Fmdetail.dfm"
#pragma resource "Foptions.dfm"
#pragma resource "Fcodes.dfm"
#pragma resource "Fprint.dfm"
#pragma resource "Frange.dfm"
#pragma resource "Fentries.dfm"
#pragma resource "Fcreated.dfm"
#pragma resource "Fschedule.dfm"
#pragma resource "Femployee.dfm"
#pragma resource "Fimport.dfm"
#pragma resource "Fmail.dfm"
//---------------------------------------------------------------------------
#define DllEntryPoint
