CREATE TABLE apps(
    APP_ID INT AUTO_INCREMENT,
    PERSONAL_ID INT NOT NULL,
    EXCLUSIVE BOOL DEFAULT 0 NOT NULL,
    CANCELLED BOOL DEFAULT 0 NOT NULL,
    PAID BOOL DEFAULT 0 NOT NULL,
    COLOR INT DEFAULT 0 NOT NULL,
    CHARGE FLOAT DEFAULT 0 NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    CREATED_BY VARCHAR (16) NOT NULL, 
    INFOTEXT VARCHAR (1024) NOT NULL,
    PRIMARY KEY(APP_ID)
) engine = innodb;

CREATE INDEX I_apps ON apps (PERSONAL_ID);
