CREATE TABLE schedules(
    SCHEDULE_ID INT AUTO_INCREMENT,
    SCHEDULE_NAME VARCHAR (16) NOT NULL,
    WEEK_START TINYINT DEFAULT 0 NOT NULL,
    WEEK_STOP TINYINT DEFAULT 7 NOT NULL,
    DAY_START TINYINT DEFAULT 8 NOT NULL,
    DAY_STOP TINYINT DEFAULT 18 NOT NULL,
    DAY_UNITS TINYINT DEFAULT 24 NOT NULL,
    HIDDEN BOOL DEFAULT 1 NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    CREATED_BY VARCHAR (16) NOT NULL,
    NOTETEXT VARCHAR (1024) NOT NULL,
    PRIMARY KEY(SCHEDULE_ID)
) engine = innodb;
