CREATE TABLE codes(
    CODE_NAME VARCHAR(16) with compression NOT NULL, 
    CODE_COLOR INT DEFAULT 0 NOT NULL,
    APP_CHARGE FLOAT DEFAULT 0 NOT NULL,
    PRIMARY KEY(CODE_NAME) 
);

CREATE UNIQUE INDEX I_codes ON codes (CODE_COLOR);
