CREATE TABLE entries(
    EMPLOYEE_ID INT NOT NULL,
    DATE_FROM DATETIME NOT NULL,
    DATE_UNTIL DATETIME NOT NULL,
    DATE_DIFF DATETIME DEFAULT #1899-12-30# NOT NULL,
    PATTERN INT DEFAULT 0 NOT NULL,
    APP_ID INT DEFAULT NULL,
    UUID UNIQUEIDENTIFIER DEFAULT GenGUID() NOT NULL
);

CREATE UNIQUE INDEX I_employee_id ON entries (EMPLOYEE_ID,DATE_UNTIL,DATE_FROM,APP_ID);
CREATE INDEX I_entries ON entries (APP_ID);
