CREATE TABLE apps(
    APP_ID INT IDENTITY(1,1),
    PERSONAL_ID INT NOT NULL,
    EXCLUSIVE TINYINT DEFAULT 0 NOT NULL,
    CANCELLED TINYINT DEFAULT 0 NOT NULL,
    PAID TINYINT DEFAULT 0 NOT NULL,
    COLOR INT DEFAULT 0 NOT NULL,
    CHARGE FLOAT DEFAULT 0 NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    CREATED_BY VARCHAR (16) NOT NULL, 
    INFOTEXT VARCHAR (1024) NOT NULL,
    PRIMARY KEY(APP_ID)
);

CREATE INDEX I_apps ON apps (PERSONAL_ID);
