CREATE TABLE personal (
    PERSONAL_ID INT IDENTITY(1,1),
    LASTNAME VARCHAR (30) NOT NULL,
    FIRSTNAME VARCHAR (30) NOT NULL,
    PREFIX VARCHAR (10) NOT NULL,
    INITIALS VARCHAR (6) NOT NULL,
    ADDRESS VARCHAR (60) NOT NULL,
    POSTCODE VARCHAR (12) NOT NULL,
    CITY VARCHAR (30) NOT NULL,
    TELEPHONE VARCHAR (16) NOT NULL,
    TELEPHONE2 VARCHAR (16) NOT NULL,
    BIRTHDATE DATETIME NOT NULL,
    HIDDEN TINYINT DEFAULT 0 NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    CREATED_BY VARCHAR (16) NOT NULL,
    MEMOTEXT VARCHAR (1024) NOT NULL,
    PRIMARY KEY(PERSONAL_ID)
);

CREATE INDEX I_lastname ON personal (LASTNAME);
CREATE INDEX I_postcode ON personal (POSTCODE);
CREATE INDEX I_address ON personal (ADDRESS);
CREATE INDEX I_city ON personal (CITY);
